### ISSUE TITLE
Add bash completion

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-tools#1]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-tools/issues/1)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
Pressing tab twice should complete with possible commands. Take the `gz` tool [for example](https://github.com/osrf/gazebo/blob/gazebo11/tools/gazebo.bash-completion), pressing tab twice displays options such as `camera`, `topic`, etc.

**Comment by scpeters** [comment]
To start investigating this, I looked briefly at `ros2cli`, since it does a very good job of tab-completing in bash. It uses [argcomplete](https://kislyuk.github.io/argcomplete/), which is based in python and automatically works for packages that express their arguments using [argparse](https://docs.python.org/3/library/argparse.html). The following files is all that is needed to enable bash-completion:

* https://github.com/ros2/ros2cli/blob/master/ros2cli/completion/ros2-argcomplete.bash

That command is sourced as part of the general ros2 setup script, I believe because of the following configuration file:

* https://github.com/ros2/ros2cli/blob/master/ros2cli/resource/package.dsv

If only we could just use `argcomplete` for `ign`! Unfortunately it does not currently use python. `ign` uses Ruby to look for `*.yaml` files in the `IGN_CONFIG_PATH` and parses these YAML files to determine the list of commands that can be executed. These command are implemented as Ruby files that either [`dlopen` a c++ library to call a function](https://github.com/ignitionrobotics/sdformat/blob/sdformat12_12.3.0/src/cmd/cmdsdformat.rb.in#L130-L158) or [pass the CLI arguments to a C++ executable](https://github.com/ignitionrobotics/ign-transport/blob/ignition-transport11_11.0.0/src/cmd/cmdtransport.rb.in#L54).

I think a first step would be to implement autocomplete for just the names of commands available in `IGN_CONFIG_PATH`. Once that is working, we can figure out how support autocomplete for the arguments to each command.

An additional reference is the [gz completion script](https://github.com/osrf/gazebo/blob/gazebo11/tools/gazebo.bash-completion) used in gazebo classic.

**Comment by scpeters** [comment]
> or [pass the CLI arguments to a C++ executable](https://github.com/ignitionrobotics/ign-transport/blob/ignition-transport11_11.0.0/src/cmd/cmdtransport.rb.in#L54).

Our executables are currently using a fork of [cli11](https://github.com/CLIUtils/CLI11) for argument parsing, which has an open feature request to support autocompletion: https://github.com/CLIUtils/CLI11/issues/343.

**Comment by scpeters** [comment]
> If only we could just use `argcomplete` for `ign`! Unfortunately it does not currently use python.

There is a way to use `argcomplete` with programs not written in python using the `--external-argcomplete-script`, but it requires writing a python script with the argument parsing logic replicated using `argparse`.

* https://kislyuk.github.io/argcomplete/#external-argcomplete-script

**Comment by scpeters** [comment]
I've started in https://github.com/ignitionrobotics/ign-tools/pull/77 by porting a portion of the `gz` completion script that autocompletes from a list of valid `ign` commands determined with `ign --commands`. It is a minimal set of functionality to demonstrate the approach.

**Comment by chapulina** [comment]
> But is there any reason to stay with Ruby?

One reason at the moment is that we don't have the time to port it to another language, which would be a large effort, so we'd need a strong reason to do so.

> I'm not sure if this is the only use of Ruby in Ignition

* This issue is related: https://github.com/ignitionrobotics/sdformat/issues/274

**Comment by mabelzhang** [comment]
Followup tasks to #87, which adds bash completion to second-level flags, i.e. `cmd subcommand --flag`:
- When forward-port gz-transport flag to Fortress, follow TODO lines in code https://github.com/gazebosim/gz-transport/pull/312#discussion_r880423460
- When forward-port gz-sim flag to Fortress, follow TODO lines in code https://github.com/gazebosim/gz-sim/pull/1504#discussion_r880427791
